/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.infox.telas;

/**
 *
 * @author MDAVEL
 */
public class TelaSobre extends javax.swing.JFrame {

    /**
     * Creates new form TelaSobre
     */
    public TelaSobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloSobre = new javax.swing.JLabel();
        lblDesenvPor = new javax.swing.JLabel();
        lblDesenvPor1 = new javax.swing.JLabel();
        lblGPL = new javax.swing.JLabel();
        lblDesenvPor2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SENAI - Informações do Sistema de Controle de O.S.");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloSobre.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTituloSobre.setForeground(new java.awt.Color(204, 0, 0));
        lblTituloSobre.setText("SENAI - Sistema d Controle de Ordens de Serviço");
        getContentPane().add(lblTituloSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 420, 20));

        lblDesenvPor.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblDesenvPor.setForeground(new java.awt.Color(0, 0, 204));
        lblDesenvPor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesenvPor.setText("Desenvolvido por Mauricio Davel");
        getContentPane().add(lblDesenvPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 450, 20));

        lblDesenvPor1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblDesenvPor1.setForeground(new java.awt.Color(204, 0, 0));
        lblDesenvPor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesenvPor1.setText("Sob Licença GPL");
        getContentPane().add(lblDesenvPor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 210, 20));

        lblGPL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGPL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/gnu.png"))); // NOI18N
        getContentPane().add(lblGPL, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 190, 170));

        lblDesenvPor2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblDesenvPor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesenvPor2.setText("Versão 1.0.1");
        getContentPane().add(lblDesenvPor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 210, 20));

        setSize(new java.awt.Dimension(486, 401));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSobre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDesenvPor;
    private javax.swing.JLabel lblDesenvPor1;
    private javax.swing.JLabel lblDesenvPor2;
    private javax.swing.JLabel lblGPL;
    private javax.swing.JLabel lblTituloSobre;
    // End of variables declaration//GEN-END:variables
}
